import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import DefaultLayout from "../layouts/DefaultLayout";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>News App | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-2.png" />
      </Head>
      <DefaultLayout>
        <div className="py-24">
          <div className="container">
            <div className="row align-items-center">
              <div className="col-12 col-lg-5 mb-10">
                <div className="display-4 mb-5 mt-n16">🚀</div>

                <h1 className="ls-tight font-bolder display-3 mb-5">
                  Read more.
                  <br />
                  Check fast.
                </h1>
                <p className="lead mb-10">
                  With a scalable and fast news app, you can check the news
                  daily.In all the topics,a good resume and trusted source make
                  you enough informed.
                </p>
                <div className="mx-n2">
                  <Link href="/news/1">
                    <a className="btn btn-lg btn-dark shadow-sm mx-2 px-lg-8">
                      Check News
                    </a>
                  </Link>
                  <Link href="/info">
                    <a className="btn btn-lg btn-neutral mx-2 px-lg-8">
                      Info Up
                    </a>
                  </Link>
                </div>
              </div>
              <div className="col-12 col-lg-6">
                <div className="w-xl-12/10 position-relative">
                  <span className="d-none d-lg-block position-absolute top-0 start-0 transform translate-x-n32 translate-y-n16 w-2/3 h-2/3 bg-warning opacity-20 rounded-circle filter blur-50"></span>
                  <span className="d-none d-xl-block position-absolute bottom-0 end-0 transform translate-x-16 translate-y-16 w-32 h-32 bg-warning opacity-60 rounded-circle filter blur-50"></span>
                  <img
                    alt="..."
                    src="https://images.unsplash.com/photo-1543269664-76bc3997d9ea?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&h=900&q=80"
                    className="shadow-4 rounded-4 position-relative overlap-10"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </DefaultLayout>
    </>
  );
}
